version = 1

exclude_patterns = ["/.cache/**/*", "/pnpm-lock.yaml", "/public/**/*", "/src/generated/**/*"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
