schema: http://localhost:10014/___graphql
documents:
  - src/**/*.{ts,tsx}
  - gatsby-node.ts
extensions:
  codegen:
    overwrite: true
    generates:
      src/generated/graphqlTypes.ts:
        plugins:
          - typescript
          - typescript-operations
    config:
      numericEnums: true
      avoidOptionals: true
      preResolveTypes: false
      maybeValue: T
      immutableTypes: true
