minimumReleaseAge: 10080

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
  workerd: true
  core-js: false
  core-js-pure: false
  es5-ext: false
  gatsby: false
  gatsby-cli: false
  gatsby-plugin-fix-fouc: false
