onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
  - workerd

ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - es5-ext
  - gatsby
  - gatsby-cli
  - gatsby-plugin-fix-fouc
