name: Deploy to Staging (stg)

on:
  push:
    branches: [stg]
  workflow_dispatch:

concurrency:
  group: deploy-to-stg
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-to-stg
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_PAT_CHECKOUT }}
          submodules: "recursive"

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            public
            .cache
          key: gatsby-v1-${{ hashFiles('public') }}
          restore-keys: |
            gatsby-v1-

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build
        env:
          # "bucketName" is a required option for gatsby-plugin-s3
          AWS_S3_BUCKET_NAME: "example"
          ALL_PAGES_TO_NO_INDEX: "true"
          GTM_ID: ${{ vars.GTM_ID }}
          PREFIX_PATHS: "true"
          GATSBY_SITE_URL: "https://bicstone.github.io/portfolio"
          PATH_PREFIX: "/portfolio"

      - run: |
          echo -e "User-agent: *\nDisallow: /" > ./public/robots.txt

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./public

      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

      - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            public
            .cache
          key: gatsby-v1-${{ hashFiles('public') }}
