name: Update submodules

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]
  push:
    branches: [main]

permissions: {}

jobs:
  update:
    runs-on: ubuntu-latest
    environment: update-submodules
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_PAT_CHECKOUT }}
          submodules: recursive

      - name: Update submodules
        run: git submodule update --remote --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GH_PAT_PR }}
          commit-message: "chore: Update submodules"
          branch: chore/update-submodules
          delete-branch: true
          title: "chore: Update submodules"
          assignees: bicstone
